backend:
  name: git-gateway
  repo: maciej790/wehikul-czasu
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł artykułu", name: "title", widget: "string" }
      - {
          label: "Obraz miniaturka",
          name: "thumbnail",
          widget: "image",
          date_format: YYYY-MM-DDTHH:mm,
        }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Czas czytania", name: "time", widget: "number" }
      # - {
      #     label: "Kategoria",
      #     name: "tags",
      #     widget: "list",
      #     summary: "{{fields.tag}}",
      #     field: { label: "Tag", name: "tag", widget: "string" },
      #   }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          searchFields: ["name"],
          valueField: "name",
        }

      - { label: "Body", name: "body", widget: "markdown" }

  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
