backend:
  name: git-gateway
  repo: maciej790/wehikul-czasu
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "UUID", name: "uuid", widget: uuid }
      - { label: "Tytuł artykułu", name: "title", widget: "string" }
      - {
          label: "Obraz miniaturka",
          name: "thumbnail",
          widget: "image",
          date_format: YYYY-MM-DDTHH:mm,
        }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Czas czytania", name: "time", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        displayFields: ["name"]
        valueField: "name"

  - name: "authors"
    label: "Authors"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    fields:
      - { label: "UUID", name: "uuid", widget: uuid }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Profile", name: "profile", widget: "markdown" }
