backend:
  name: git-gateway
  repo: maciej790/wehikul-czasu
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "id" }
      - { label: "Tytuł artykułu", name: "title", widget: "string" }
      - {
          label: "Obraz miniaturka",
          name: "thumbnail",
          widget: "image",
          date_format: YYYY-MM-DDTHH:mm,
        }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Czas czytania", name: "time", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        searchFields: ["name"]
        displayFields: ["name"]
        valueField: "id"

  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    fields:
      - { label: "ID", name: "id", widget: "id" }
      - { label: "Name", name: "name", widget: "string" }
